### ISSUE TITLE
I can't clone adonisx-example repo with adonisx-cli

### ISSUE THREAD

**Issue by YusufSina** [adonisx/adonisx#5]
I was looking for learning AdonisX and tried to practise but I couldn't. I was reading get started section and after setting up adonisx-cli, tried to '$ adonisx new my-api' and got this problem.

![screenshot](https://user-images.githubusercontent.com/37187996/80311509-b3631900-87e8-11ea-847c-4e72c99d5314.PNG)

I am wondering that this problem is because of me or not. I guess it is about SSH and HTTPS. but I don't know what to do. Thanks for your help

**Comment by ozziest** [comment]
Thank you very much for feedback. :heartbeat: 

Actually this is a known issue about [adonisx-cli - #1](https://github.com/adonisx/adonisx-cli/issues/1)

I created *adonisx-cli* on Ubuntu and I couldn't test it on Windows. We are going to fix this bug as soon as possible.

**Comment by YusufSina** [comment]
Fixed
