### ISSUE TITLE
Pagination results scheme

### ISSUE THREAD

**Issue by teathedev** [adonisx/adonisx#6]
Pagination result scheme can be like that;
```
{
  "page": 1,
  "limit": 10,
  "count": 252,
  "results": [
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ]
}
```

I think that way more pretty then current scheme

**Comment by ozziest** [comment]
Thank your very much for your feedback. :heart: :dancers: 

But we are using the pagination structure of [AdonisJs](https://adonisjs.com/docs/4.1/lucid#_pagination)

```js
const users = await User.query().paginate(page)
```

```json
{
  "total": "",
  "perPage": "",
  "lastPage": "",
  "page": "",
  "data": []
}
```

So it is the structure of AdonisJs, not us. And I am not sure to change it.

**Comment by ismaildenzzz** [comment]
Thanks for the feedback. But I don't think the response structure is more illegible, in fact, it basically contains all the areas that might be needed.
