### ISSUE TITLE
Different validation rules for creating and updating

### ISSUE THREAD

**Issue by ozziest** [adonisx/adonisx#7]
Let's assume that I have a `User` model like this;

```js
class User extends XModel {
  static get validations () {
    return {
      email: 'required|email|max:100',
      name: 'required|max:50',
      password: 'required|min:8|max:20'
    }
  }
}
```

In this model, I should be able to select different validation rules for creating and updating. Because, in creation, I should verify email and password. But in updating my user information I don't need to verify email and password data again. It should be able to select differently.

For example, we can have a structure like this; If I have a simple model, we can use that for creating and updating;

```js
class User extends XModel {
  static get validations () {
    return {
      email: 'required|email|max:100',
      name: 'required|max:50',
      password: 'required|min:8|max:20'
    }
  }
}
```

But if I want to describe the more specific structure, I can define validation rules like this; 

```js
class User extends XModel {
  static get validations () {
    return {
      POST: {
        email: 'required|email|max:100',
        name: 'required|max:50',
        password: 'required|min:8|max:20'
      },
      PUT: {
        name: 'required|max:50'
      }
    }
  }
}
```

This structure can be useful but it is open to discussing.

**Comment by ozziest** [comment]
In addition, developers should be able to select which fields are fillable in **creating** and **updating**. Otherwise, the new form validation structure doesn't help developers.

For example;

```js
class Users extends XModel {
  static get fillable () {
    return {
      POST: ['email', 'name', 'surname', 'age'],
      PUT: ['name', 'surname', 'age']
    }
  }
}
```
But also we should keep original structure if we want to use same fillable fields in creating and updating actions.

**Comment by ismaildenzzz** [comment]
It can be useful for the structure. Actually, the main problem here is that the domain model and business model are the same.

But the separation of business models can be counterproductive to the project structure. **Therefore I find custom model validation sufficient based on the HTTP request type.**
